/**:
  ros__parameters:
    filter1:
      name: polygon_filter
      type: laser_filters/LaserScanPolygonFilter
      params:
        polygon_frame: base_link
        polygon: '[[-0.25, -0.20], [0.25, -0.20], [0.25, 0.20], [-0.25, 0.20]]'
        invert: false
